name: snd_rental_mobile_app
description: "SND Rental Management System Mobile App - Cross-platform Flutter application for rental management, employee management, and project tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Authentication
  google_sign_in: ^6.2.1
  # firebase_auth: ^4.15.3
  # firebase_core: ^2.24.2
  flutter_secure_storage: ^9.0.0

  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path: ^1.8.3

  # UI Components
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Device Integration
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  mobile_scanner: ^3.5.6

  # Notifications
  # firebase_messaging: ^14.7.10
  # flutter_local_notifications: ^16.3.0  # Temporarily disabled due to build issues

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  logger: ^2.0.2+1
  
  # Deep Links (temporarily disabled due to Android build issues)
  # app_links: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # Fonts
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700