export const saudiCities = [
  // Major Cities
  {
    name: "Riyadh",
    description: "Capital and largest city of Saudi Arabia",
    city: "Riyadh",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.7136,
    longitude: 46.6753,
  },
  {
    name: "Jeddah",
    description: "Major port city on the Red Sea",
    city: "Jeddah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.4858,
    longitude: 39.1925,
  },
  {
    name: "Mecca",
    description: "Holiest city in Islam",
    city: "Mecca",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.4225,
    longitude: 39.8262,
  },
  {
    name: "Medina",
    description: "Second holiest city in Islam",
    city: "Medina",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.5247,
    longitude: 39.5692,
  },
  {
    name: "Dammam",
    description: "Capital of Eastern Province",
    city: "Dammam",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.4207,
    longitude: 50.0888,
  },
  {
    name: "Khobar",
    description: "Major city in Eastern Province",
    city: "Khobar",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2172,
    longitude: 50.1971,
  },
  {
    name: "Dhahran",
    description: "Oil industry center",
    city: "Dhahran",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2361,
    longitude: 50.0393,
  },
  {
    name: "Jubail",
    description: "Industrial city on the Persian Gulf",
    city: "Jubail",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 27.0049,
    longitude: 49.6580,
  },
  {
    name: "Abha",
    description: "Capital of Asir Province",
    city: "Abha",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.2164,
    longitude: 42.5053,
  },
  {
    name: "Taif",
    description: "Mountain city in Makkah Province",
    city: "Taif",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.2703,
    longitude: 40.4158,
  },
  {
    name: "Tabuk",
    description: "Capital of Tabuk Province",
    city: "Tabuk",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 28.3998,
    longitude: 36.5715,
  },
  {
    name: "Hail",
    description: "Capital of Hail Province",
    city: "Hail",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.5111,
    longitude: 41.7208,
  },
  {
    name: "Najran",
    description: "Capital of Najran Province",
    city: "Najran",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.5656,
    longitude: 44.2289,
  },
  {
    name: "Jizan",
    description: "Capital of Jizan Province",
    city: "Jizan",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.8894,
    longitude: 42.5706,
  },
  {
    name: "Al-Ahsa",
    description: "Oasis region in Eastern Province",
    city: "Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3832,
    longitude: 49.5877,
  },
  {
    name: "Al-Kharj",
    description: "Agricultural city near Riyadh",
    city: "Al-Kharj",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.1554,
    longitude: 47.3346,
  },
  {
    name: "Al-Qassim",
    description: "Agricultural region",
    city: "Buraydah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.3020,
    longitude: 43.9720,
  },
  {
    name: "Al-Jouf",
    description: "Capital of Al-Jouf Province",
    city: "Sakaka",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 29.9697,
    longitude: 40.1004,
  },
  {
    name: "Al-Baha",
    description: "Capital of Al-Baha Province",
    city: "Al-Baha",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 20.0129,
    longitude: 41.4677,
  },
  {
    name: "Northern Borders",
    description: "Capital of Northern Borders Province",
    city: "Arar",
    state: "Northern Borders Province",
    country: "Saudi Arabia",
    latitude: 30.9753,
    longitude: 41.0381,
  },
  // Additional Major Cities
  {
    name: "Yanbu",
    description: "Industrial port city",
    city: "Yanbu",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.0895,
    longitude: 38.0617,
  },
  {
    name: "Ras Tanura",
    description: "Oil terminal city",
    city: "Ras Tanura",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 50.1667,
  },
  {
    name: "Al-Khafji",
    description: "Border city with Kuwait",
    city: "Al-Khafji",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 28.4391,
    longitude: 48.4913,
  },
  {
    name: "Al-Qatif",
    description: "Historical city in Eastern Province",
    city: "Al-Qatif",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5765,
    longitude: 49.9982,
  },
  {
    name: "Al-Hofuf",
    description: "Major city in Al-Ahsa",
    city: "Al-Hofuf",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3832,
    longitude: 49.5877,
  },
  {
    name: "Al-Mubarraz",
    description: "City in Al-Ahsa region",
    city: "Al-Mubarraz",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.5833,
  },
  {
    name: "Al-Khobar",
    description: "Major city in Eastern Province",
    city: "Al-Khobar",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2172,
    longitude: 50.1971,
  },
  {
    name: "Al-Dammam",
    description: "Capital of Eastern Province",
    city: "Al-Dammam",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.4207,
    longitude: 50.0888,
  },
  {
    name: "Al-Jubail",
    description: "Industrial city",
    city: "Al-Jubail",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 27.0049,
    longitude: 49.6580,
  },
  {
    name: "Al-Riyadh",
    description: "Capital city",
    city: "Al-Riyadh",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.7136,
    longitude: 46.6753,
  },
  {
    name: "Al-Jeddah",
    description: "Port city",
    city: "Al-Jeddah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.4858,
    longitude: 39.1925,
  },
  {
    name: "Al-Makkah",
    description: "Holy city",
    city: "Al-Makkah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.4225,
    longitude: 39.8262,
  },
  {
    name: "Al-Madinah",
    description: "Holy city",
    city: "Al-Madinah",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.5247,
    longitude: 39.5692,
  },
  {
    name: "Al-Taif",
    description: "Mountain city",
    city: "Al-Taif",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.2703,
    longitude: 40.4158,
  },
  {
    name: "Al-Abha",
    description: "Mountain city",
    city: "Al-Abha",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.2164,
    longitude: 42.5053,
  },
  {
    name: "Al-Tabuk",
    description: "Northern city",
    city: "Al-Tabuk",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 28.3998,
    longitude: 36.5715,
  },
  {
    name: "Al-Hail",
    description: "Central city",
    city: "Al-Hail",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.5111,
    longitude: 41.7208,
  },
  {
    name: "Al-Najran",
    description: "Southern city",
    city: "Al-Najran",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.5656,
    longitude: 44.2289,
  },
  {
    name: "Al-Jizan",
    description: "Southern port city",
    city: "Al-Jizan",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.8894,
    longitude: 42.5706,
  },
  {
    name: "Al-Baha",
    description: "Mountain city",
    city: "Al-Baha",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 20.0129,
    longitude: 41.4677,
  },
  {
    name: "Al-Arar",
    description: "Northern city",
    city: "Al-Arar",
    state: "Northern Borders Province",
    country: "Saudi Arabia",
    latitude: 30.9753,
    longitude: 41.0381,
  },
  {
    name: "Al-Sakaka",
    description: "Northern city",
    city: "Al-Sakaka",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 29.9697,
    longitude: 40.1004,
  },
  {
    name: "Al-Buraydah",
    description: "Central city",
    city: "Al-Buraydah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.3020,
    longitude: 43.9720,
  },
  {
    name: "Al-Kharj",
    description: "Agricultural city",
    city: "Al-Kharj",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.1554,
    longitude: 47.3346,
  },
  {
    name: "Al-Yanbu",
    description: "Industrial city",
    city: "Al-Yanbu",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.0895,
    longitude: 38.0617,
  },
  {
    name: "Al-Ras Tanura",
    description: "Oil terminal",
    city: "Al-Ras Tanura",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 50.1667,
  },
  {
    name: "Al-Khafji",
    description: "Border city",
    city: "Al-Khafji",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 28.4391,
    longitude: 48.4913,
  },
  {
    name: "Al-Qatif",
    description: "Historical city",
    city: "Al-Qatif",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5765,
    longitude: 49.9982,
  },
  {
    name: "Al-Hofuf",
    description: "Oasis city",
    city: "Al-Hofuf",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3832,
    longitude: 49.5877,
  },
  {
    name: "Al-Mubarraz",
    description: "Oasis city",
    city: "Al-Mubarraz",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.5833,
  },
  // Local Cities - Riyadh Province
  {
    name: "Al-Diriyah",
    description: "Historical city and UNESCO World Heritage site",
    city: "Al-Diriyah",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.7333,
    longitude: 46.5833,
  },
  {
    name: "Al-Kharj",
    description: "Agricultural city and major food producer",
    city: "Al-Kharj",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.1554,
    longitude: 47.3346,
  },
  {
    name: "Al-Majma'ah",
    description: "Agricultural city in northern Riyadh region",
    city: "Al-Majma'ah",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 25.9000,
    longitude: 45.3667,
  },
  {
    name: "Al-Zulfi",
    description: "Agricultural city in northern Riyadh region",
    city: "Al-Zulfi",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 26.3000,
    longitude: 44.8000,
  },
  {
    name: "Al-Ghat",
    description: "Mountain city in western Riyadh region",
    city: "Al-Ghat",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 26.1500,
    longitude: 44.2000,
  },
  {
    name: "Al-Dawadmi",
    description: "Agricultural city in western Riyadh region",
    city: "Al-Dawadmi",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.5000,
    longitude: 44.4000,
  },
  {
    name: "Al-Aflaj",
    description: "Agricultural city in southern Riyadh region",
    city: "Al-Aflaj",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 22.3000,
    longitude: 46.7000,
  },
  {
    name: "Al-Quway'iyah",
    description: "Agricultural city in southern Riyadh region",
    city: "Al-Quway'iyah",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 24.4500,
    longitude: 45.3500,
  },
  {
    name: "Al-Hariq",
    description: "Mountain city in western Riyadh region",
    city: "Al-Hariq",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 25.4500,
    longitude: 45.2500,
  },
  {
    name: "Al-Rumah",
    description: "Agricultural city in northern Riyadh region",
    city: "Al-Rumah",
    state: "Riyadh Province",
    country: "Saudi Arabia",
    latitude: 25.7000,
    longitude: 45.8500,
  },
  // Local Cities - Makkah Province
  {
    name: "Rabigh",
    description: "Coastal city on the Red Sea",
    city: "Rabigh",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 22.8000,
    longitude: 39.0333,
  },
  {
    name: "Al-Lith",
    description: "Coastal city on the Red Sea",
    city: "Al-Lith",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 20.1500,
    longitude: 40.2833,
  },
  {
    name: "Al-Qunfudhah",
    description: "Coastal city on the Red Sea",
    city: "Al-Qunfudhah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 19.1333,
    longitude: 41.0833,
  },
  {
    name: "Al-Kamil",
    description: "Agricultural city in Makkah region",
    city: "Al-Kamil",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 22.2333,
    longitude: 39.2000,
  },
  {
    name: "Al-Jumum",
    description: "Agricultural city near Makkah",
    city: "Al-Jumum",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.6167,
    longitude: 39.7000,
  },
  {
    name: "Al-Khurmah",
    description: "Agricultural city in Taif region",
    city: "Al-Khurmah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.9000,
    longitude: 42.1333,
  },
  {
    name: "Turubah",
    description: "Agricultural city in Taif region",
    city: "Turubah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.2667,
    longitude: 41.6333,
  },
  {
    name: "Ranyah",
    description: "Agricultural city in Taif region",
    city: "Ranyah",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 21.2000,
    longitude: 42.7000,
  },
  {
    name: "Al-Muwayh",
    description: "Agricultural city in Taif region",
    city: "Al-Muwayh",
    state: "Makkah Province",
    country: "Saudi Arabia",
    latitude: 22.4333,
    longitude: 41.1333,
  },
  // Local Cities - Al Madinah Province
  {
    name: "Al-'Ula",
    description: "Historical city and UNESCO World Heritage site",
    city: "Al-'Ula",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 26.6167,
    longitude: 37.9167,
  },
  {
    name: "Khaybar",
    description: "Historical oasis city",
    city: "Khaybar",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 25.0000,
    longitude: 39.5000,
  },
  {
    name: "Al-Hinakiyah",
    description: "Agricultural city in Madinah region",
    city: "Al-Hinakiyah",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.8000,
    longitude: 39.3000,
  },
  {
    name: "Al-Mahd",
    description: "Agricultural city in Madinah region",
    city: "Al-Mahd",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 23.5000,
    longitude: 38.6000,
  },
  {
    name: "Al-Rawdah",
    description: "Agricultural city in Madinah region",
    city: "Al-Rawdah",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.4000,
    longitude: 38.6000,
  },
  {
    name: "Al-Masani'",
    description: "Agricultural city in Madinah region",
    city: "Al-Masani'",
    state: "Al Madinah Province",
    country: "Saudi Arabia",
    latitude: 24.2000,
    longitude: 38.5000,
  },
  // Local Cities - Eastern Province
  {
    name: "Al-Jubayl",
    description: "Industrial city and port",
    city: "Al-Jubayl",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 27.0049,
    longitude: 49.6580,
  },
  {
    name: "Al-Khafji",
    description: "Border city with Kuwait",
    city: "Al-Khafji",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 28.4391,
    longitude: 48.4913,
  },
  {
    name: "Al-Nu'ayriyah",
    description: "Agricultural city in Eastern Province",
    city: "Al-Nu'ayriyah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 27.4708,
    longitude: 48.4808,
  },
  {
    name: "Al-Awamiyah",
    description: "Historical city in Qatif region",
    city: "Al-Awamiyah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5833,
    longitude: 49.9833,
  },
  {
    name: "Al-Safwa",
    description: "Industrial city in Eastern Province",
    city: "Al-Safwa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 49.9500,
  },
  {
    name: "Al-Qaryat Al-'Ulya",
    description: "Agricultural city in Al-Ahsa",
    city: "Al-Qaryat Al-'Ulya",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.6000,
  },
  {
    name: "Al-Mubarraz",
    description: "Major city in Al-Ahsa oasis",
    city: "Al-Mubarraz",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.5833,
  },
  {
    name: "Al-Hofuf",
    description: "Major city in Al-Ahsa oasis",
    city: "Al-Hofuf",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3832,
    longitude: 49.5877,
  },
  {
    name: "Al-Qatif",
    description: "Historical city in Eastern Province",
    city: "Al-Qatif",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5765,
    longitude: 49.9982,
  },
  {
    name: "Al-Dammam",
    description: "Capital of Eastern Province",
    city: "Al-Dammam",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.4207,
    longitude: 50.0888,
  },
  {
    name: "Al-Khobar",
    description: "Major city in Eastern Province",
    city: "Al-Khobar",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2172,
    longitude: 50.1971,
  },
  {
    name: "Dhahran",
    description: "Oil industry center",
    city: "Dhahran",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2361,
    longitude: 50.0393,
  },
  {
    name: "Ras Tanura",
    description: "Oil terminal city",
    city: "Ras Tanura",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 50.1667,
  },
  // Local Cities - Asir Province
  {
    name: "Khamis Mushait",
    description: "Major city in Asir Province",
    city: "Khamis Mushait",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.3000,
    longitude: 42.7333,
  },
  {
    name: "Abha",
    description: "Capital of Asir Province",
    city: "Abha",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.2164,
    longitude: 42.5053,
  },
  {
    name: "Al-Namas",
    description: "Mountain city in Asir Province",
    city: "Al-Namas",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 19.1500,
    longitude: 42.1167,
  },
  {
    name: "Bishah",
    description: "Agricultural city in Asir Province",
    city: "Bishah",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 20.0000,
    longitude: 42.6000,
  },
  {
    name: "Al-Rijal Alma'",
    description: "Historical village in Asir Province",
    city: "Al-Rijal Alma'",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.2167,
    longitude: 42.4167,
  },
  {
    name: "Rijal Alma'",
    description: "UNESCO World Heritage site village",
    city: "Rijal Alma'",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.2167,
    longitude: 42.4167,
  },
  {
    name: "Al-Sarah",
    description: "Mountain village in Asir Province",
    city: "Al-Sarah",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.3000,
    longitude: 42.7000,
  },
  {
    name: "Al-Majardah",
    description: "Mountain village in Asir Province",
    city: "Al-Majardah",
    state: "Asir Province",
    country: "Saudi Arabia",
    latitude: 18.2500,
    longitude: 42.5000,
  },
  // Local Cities - Tabuk Province
  {
    name: "Tabuk",
    description: "Capital of Tabuk Province",
    city: "Tabuk",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 28.3998,
    longitude: 36.5715,
  },
  {
    name: "Al-Wajh",
    description: "Coastal city on the Red Sea",
    city: "Al-Wajh",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 26.2333,
    longitude: 36.4667,
  },
  {
    name: "Duba",
    description: "Coastal city on the Red Sea",
    city: "Duba",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 27.3500,
    longitude: 35.7000,
  },
  {
    name: "Haql",
    description: "Coastal city on the Red Sea",
    city: "Haql",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 29.2833,
    longitude: 34.9500,
  },
  {
    name: "Al-Bad'",
    description: "Agricultural city in Tabuk region",
    city: "Al-Bad'",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 28.5000,
    longitude: 35.0000,
  },
  {
    name: "Tayma",
    description: "Historical oasis city",
    city: "Tayma",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 27.6167,
    longitude: 38.5333,
  },
  {
    name: "Al-'Uqayr",
    description: "Historical port city",
    city: "Al-'Uqayr",
    state: "Tabuk Province",
    country: "Saudi Arabia",
    latitude: 26.4833,
    longitude: 50.1000,
  },
  // Local Cities - Hail Province
  {
    name: "Hail",
    description: "Capital of Hail Province",
    city: "Hail",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.5111,
    longitude: 41.7208,
  },
  {
    name: "Al-Ghazalah",
    description: "Agricultural city in Hail region",
    city: "Al-Ghazalah",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.7000,
    longitude: 41.9000,
  },
  {
    name: "Al-Shinan",
    description: "Agricultural city in Hail region",
    city: "Al-Shinan",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.8000,
    longitude: 41.9500,
  },
  {
    name: "Al-Samirah",
    description: "Agricultural city in Hail region",
    city: "Al-Samirah",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.6000,
    longitude: 41.8000,
  },
  {
    name: "Al-Raq'i",
    description: "Agricultural city in Hail region",
    city: "Al-Raq'i",
    state: "Hail Province",
    country: "Saudi Arabia",
    latitude: 27.5000,
    longitude: 41.6000,
  },
  // Local Cities - Najran Province
  {
    name: "Najran",
    description: "Capital of Najran Province",
    city: "Najran",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.5656,
    longitude: 44.2289,
  },
  {
    name: "Sharurah",
    description: "Border city with Yemen",
    city: "Sharurah",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.4833,
    longitude: 47.1167,
  },
  {
    name: "Al-Khubash",
    description: "Agricultural city in Najran region",
    city: "Al-Khubash",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.3500,
    longitude: 44.2000,
  },
  {
    name: "Al-Akhdud",
    description: "Agricultural city in Najran region",
    city: "Al-Akhdud",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.5000,
    longitude: 44.3000,
  },
  {
    name: "Al-Wadiah",
    description: "Border crossing with Yemen",
    city: "Al-Wadiah",
    state: "Najran Province",
    country: "Saudi Arabia",
    latitude: 17.4333,
    longitude: 47.1000,
  },
  // Local Cities - Jizan Province
  {
    name: "Jizan",
    description: "Capital of Jizan Province",
    city: "Jizan",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.8894,
    longitude: 42.5706,
  },
  {
    name: "Abu Arish",
    description: "Agricultural city in Jizan region",
    city: "Abu Arish",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.9667,
    longitude: 42.8333,
  },
  {
    name: "Al-Aridhah",
    description: "Agricultural city in Jizan region",
    city: "Al-Aridhah",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.9000,
    longitude: 42.7000,
  },
  {
    name: "Al-Harth",
    description: "Agricultural city in Jizan region",
    city: "Al-Harth",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.8000,
    longitude: 42.6000,
  },
  {
    name: "Al-Raith",
    description: "Agricultural city in Jizan region",
    city: "Al-Raith",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.7000,
    longitude: 42.5000,
  },
  {
    name: "Al-Dayr",
    description: "Agricultural city in Jizan region",
    city: "Al-Dayr",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.6000,
    longitude: 42.4000,
  },
  {
    name: "Al-'Idabi",
    description: "Agricultural city in Jizan region",
    city: "Al-'Idabi",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.5000,
    longitude: 42.3000,
  },
  {
    name: "Al-'Aridhah",
    description: "Agricultural city in Jizan region",
    city: "Al-'Aridhah",
    state: "Jizan Province",
    country: "Saudi Arabia",
    latitude: 16.4000,
    longitude: 42.2000,
  },
  // Local Cities - Al-Baha Province
  {
    name: "Al-Baha",
    description: "Capital of Al-Baha Province",
    city: "Al-Baha",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 20.0129,
    longitude: 41.4677,
  },
  {
    name: "Al-Mikhwah",
    description: "Agricultural city in Al-Baha region",
    city: "Al-Mikhwah",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 19.8000,
    longitude: 41.4000,
  },
  {
    name: "Al-'Aqiq",
    description: "Agricultural city in Al-Baha region",
    city: "Al-'Aqiq",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 20.2000,
    longitude: 41.6000,
  },
  {
    name: "Al-Qura",
    description: "Agricultural city in Al-Baha region",
    city: "Al-Qura",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 20.4000,
    longitude: 41.8000,
  },
  {
    name: "Al-Hajrah",
    description: "Agricultural city in Al-Baha region",
    city: "Al-Hajrah",
    state: "Al-Baha Province",
    country: "Saudi Arabia",
    latitude: 20.6000,
    longitude: 42.0000,
  },
  // Local Cities - Northern Borders Province
  {
    name: "Arar",
    description: "Capital of Northern Borders Province",
    city: "Arar",
    state: "Northern Borders Province",
    country: "Saudi Arabia",
    latitude: 30.9753,
    longitude: 41.0381,
  },
  {
    name: "Al-'Uwayqilah",
    description: "Agricultural city in Northern Borders",
    city: "Al-'Uwayqilah",
    state: "Northern Borders Province",
    country: "Saudi Arabia",
    latitude: 30.8000,
    longitude: 41.2000,
  },
  {
    name: "Al-Rafha",
    description: "Agricultural city in Northern Borders",
    city: "Al-Rafha",
    state: "Northern Borders Province",
    country: "Saudi Arabia",
    latitude: 29.6333,
    longitude: 43.5167,
  },
  {
    name: "Al-Turaif",
    description: "Agricultural city in Northern Borders",
    city: "Al-Turaif",
    state: "Northern Borders Province",
    country: "Saudi Arabia",
    latitude: 31.6833,
    longitude: 38.6500,
  },
  // Local Cities - Al-Jouf Province
  {
    name: "Sakaka",
    description: "Capital of Al-Jouf Province",
    city: "Sakaka",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 29.9697,
    longitude: 40.1004,
  },
  {
    name: "Al-Qurayyat",
    description: "Major city in Al-Jouf Province",
    city: "Al-Qurayyat",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 31.3333,
    longitude: 37.3333,
  },
  {
    name: "Dumat Al-Jandal",
    description: "Historical city in Al-Jouf Province",
    city: "Dumat Al-Jandal",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 29.8167,
    longitude: 39.8667,
  },
  {
    name: "Al-'Isawiyah",
    description: "Agricultural city in Al-Jouf region",
    city: "Al-'Isawiyah",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 30.0000,
    longitude: 40.2000,
  },
  {
    name: "Al-Hadithah",
    description: "Agricultural city in Al-Jouf region",
    city: "Al-Hadithah",
    state: "Al-Jouf Province",
    country: "Saudi Arabia",
    latitude: 30.2000,
    longitude: 40.4000,
  },
  // Local Cities - Al-Qassim Province
  {
    name: "Buraydah",
    description: "Capital of Al-Qassim Province",
    city: "Buraydah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.3020,
    longitude: 43.9720,
  },
  {
    name: "Unaizah",
    description: "Major city in Al-Qassim Province",
    city: "Unaizah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.0833,
    longitude: 43.9833,
  },
  {
    name: "Al-Rass",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Rass",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 25.8500,
    longitude: 43.5000,
  },
  {
    name: "Al-Bukayriyah",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Bukayriyah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.1500,
    longitude: 43.6500,
  },
  {
    name: "Al-Badai'",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Badai'",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.4500,
    longitude: 44.1500,
  },
  {
    name: "Al-Asyah",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Asyah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.5500,
    longitude: 44.2500,
  },
  {
    name: "Al-Shamasiyah",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Shamasiyah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 44.3500,
  },
  {
    name: "Al-Nabhaniyah",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Nabhaniyah",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 26.7500,
    longitude: 44.4500,
  },
  {
    name: "Al-Midhnab",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Midhnab",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 25.8500,
    longitude: 43.5500,
  },
  {
    name: "Al-Khabra",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Khabra",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 25.9500,
    longitude: 43.6500,
  },
  {
    name: "Al-Dawadmi",
    description: "Agricultural city in Al-Qassim region",
    city: "Al-Dawadmi",
    state: "Al-Qassim Province",
    country: "Saudi Arabia",
    latitude: 24.5000,
    longitude: 44.4000,
  },
  // Additional Al-Ahsa and Hardh Area Cities
  {
    name: "Al-Hardh",
    description: "Major city in Al-Ahsa region",
    city: "Al-Hardh",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4500,
    longitude: 49.6000,
  },
  {
    name: "Al-Jubail Al-Ahsa",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Jubail Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.5000,
    longitude: 49.6500,
  },
  {
    name: "Al-Umran",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Umran",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3500,
    longitude: 49.5500,
  },
  {
    name: "Al-Shu'bah",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Shu'bah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.5800,
  },
  {
    name: "Al-Jishah",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Jishah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4200,
    longitude: 49.5900,
  },
  {
    name: "Al-Mansuriyah",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Mansuriyah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3800,
    longitude: 49.5700,
  },
  {
    name: "Al-Nu'ayriyah Al-Ahsa",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Nu'ayriyah Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3600,
    longitude: 49.5600,
  },
  {
    name: "Al-Khaldiyah",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Khaldiyah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4400,
    longitude: 49.6100,
  },
  {
    name: "Al-Rumailah",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Rumailah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4600,
    longitude: 49.6200,
  },
  {
    name: "Al-Qarah",
    description: "Historical city in Al-Ahsa region",
    city: "Al-Qarah",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4100,
    longitude: 49.6800,
  },
  {
    name: "Al-Awamiyah Al-Ahsa",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Awamiyah Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4300,
    longitude: 49.6400,
  },
  {
    name: "Al-Mubarraz Al-Ahsa",
    description: "Major city in Al-Ahsa oasis",
    city: "Al-Mubarraz Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.5833,
  },
  {
    name: "Al-Hofuf Al-Ahsa",
    description: "Major city in Al-Ahsa oasis",
    city: "Al-Hofuf Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3832,
    longitude: 49.5877,
  },
  {
    name: "Al-Qatif Al-Ahsa",
    description: "Historical city in Al-Ahsa region",
    city: "Al-Qatif Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5765,
    longitude: 49.9982,
  },
  {
    name: "Al-Dammam Al-Ahsa",
    description: "Capital of Eastern Province",
    city: "Al-Dammam Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.4207,
    longitude: 50.0888,
  },
  {
    name: "Al-Khobar Al-Ahsa",
    description: "Major city in Eastern Province",
    city: "Al-Khobar Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2172,
    longitude: 50.1971,
  },
  {
    name: "Al-Jubail Al-Ahsa Industrial",
    description: "Industrial city in Al-Ahsa region",
    city: "Al-Jubail Al-Ahsa Industrial",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 27.0049,
    longitude: 49.6580,
  },
  {
    name: "Al-Ras Tanura Al-Ahsa",
    description: "Oil terminal in Al-Ahsa region",
    city: "Al-Ras Tanura Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 50.1667,
  },
  {
    name: "Al-Khafji Al-Ahsa",
    description: "Border city with Kuwait in Al-Ahsa region",
    city: "Al-Khafji Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 28.4391,
    longitude: 48.4913,
  },
  {
    name: "Al-Nu'ayriyah Al-Ahsa Industrial",
    description: "Industrial city in Al-Ahsa region",
    city: "Al-Nu'ayriyah Al-Ahsa Industrial",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 27.4708,
    longitude: 48.4808,
  },
  {
    name: "Al-Awamiyah Al-Ahsa Historical",
    description: "Historical city in Al-Ahsa region",
    city: "Al-Awamiyah Al-Ahsa Historical",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5833,
    longitude: 49.9833,
  },
  {
    name: "Al-Safwa Al-Ahsa",
    description: "Industrial city in Al-Ahsa region",
    city: "Al-Safwa Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 49.9500,
  },
  {
    name: "Al-Qaryat Al-'Ulya Al-Ahsa",
    description: "Agricultural city in Al-Ahsa region",
    city: "Al-Qaryat Al-'Ulya Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.6000,
  },
  {
    name: "Al-Mubarraz Al-Ahsa Agricultural",
    description: "Agricultural city in Al-Ahsa oasis",
    city: "Al-Mubarraz Al-Ahsa Agricultural",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.4000,
    longitude: 49.5833,
  },
  {
    name: "Al-Hofuf Al-Ahsa Agricultural",
    description: "Agricultural city in Al-Ahsa oasis",
    city: "Al-Hofuf Al-Ahsa Agricultural",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 25.3832,
    longitude: 49.5877,
  },
  {
    name: "Al-Qatif Al-Ahsa Historical",
    description: "Historical city in Al-Ahsa region",
    city: "Al-Qatif Al-Ahsa Historical",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.5765,
    longitude: 49.9982,
  },
  {
    name: "Al-Dammam Al-Ahsa Industrial",
    description: "Industrial city in Al-Ahsa region",
    city: "Al-Dammam Al-Ahsa Industrial",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.4207,
    longitude: 50.0888,
  },
  {
    name: "Al-Khobar Al-Ahsa Industrial",
    description: "Industrial city in Al-Ahsa region",
    city: "Al-Khobar Al-Ahsa Industrial",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2172,
    longitude: 50.1971,
  },
  {
    name: "Dhahran Al-Ahsa",
    description: "Oil industry center in Al-Ahsa region",
    city: "Dhahran Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.2361,
    longitude: 50.0393,
  },
  {
    name: "Ras Tanura Al-Ahsa",
    description: "Oil terminal in Al-Ahsa region",
    city: "Ras Tanura Al-Ahsa",
    state: "Eastern Province",
    country: "Saudi Arabia",
    latitude: 26.6500,
    longitude: 50.1667,
  }
];
