CREATE TABLE "final_settlements" (
	"id" serial PRIMARY KEY NOT NULL,
	"employee_id" integer NOT NULL,
	"resignation_id" integer,
	"settlement_number" text NOT NULL,
	"employee_name" text NOT NULL,
	"file_number" text,
	"iqama_number" text,
	"nationality" text,
	"designation" text,
	"department" text,
	"hire_date" date NOT NULL,
	"last_working_date" date NOT NULL,
	"total_service_years" integer NOT NULL,
	"total_service_months" integer NOT NULL,
	"total_service_days" integer NOT NULL,
	"last_basic_salary" numeric(10, 2) NOT NULL,
	"last_allowances" numeric(10, 2) DEFAULT '0',
	"unpaid_salary_months" integer DEFAULT 0 NOT NULL,
	"unpaid_salary_amount" numeric(10, 2) DEFAULT '0',
	"end_of_service_benefit" numeric(10, 2) NOT NULL,
	"benefit_calculation_method" text NOT NULL,
	"accrued_vacation_days" integer DEFAULT 0,
	"accrued_vacation_amount" numeric(10, 2) DEFAULT '0',
	"other_benefits" numeric(10, 2) DEFAULT '0',
	"other_benefits_description" text,
	"pending_advances" numeric(10, 2) DEFAULT '0',
	"equipment_deductions" numeric(10, 2) DEFAULT '0',
	"other_deductions" numeric(10, 2) DEFAULT '0',
	"other_deductions_description" text,
	"gross_amount" numeric(10, 2) NOT NULL,
	"total_deductions" numeric(10, 2) NOT NULL,
	"net_amount" numeric(10, 2) NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"notes" text,
	"prepared_by" integer NOT NULL,
	"prepared_at" date DEFAULT CURRENT_DATE NOT NULL,
	"approved_by" integer,
	"approved_at" date,
	"paid_by" integer,
	"paid_at" date,
	"payment_method" text,
	"payment_reference" text,
	"pdf_path" text,
	"employee_signature_date" date,
	"company_signature_date" date,
	"currency" text DEFAULT 'SAR' NOT NULL,
	"created_at" date DEFAULT CURRENT_DATE NOT NULL,
	"updated_at" date NOT NULL,
	CONSTRAINT "final_settlements_settlement_number_unique" UNIQUE("settlement_number")
);
--> statement-breakpoint
ALTER TABLE "final_settlements" ADD CONSTRAINT "final_settlements_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "final_settlements" ADD CONSTRAINT "final_settlements_resignation_id_fkey" FOREIGN KEY ("resignation_id") REFERENCES "public"."employee_resignations"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "final_settlements" ADD CONSTRAINT "final_settlements_prepared_by_fkey" FOREIGN KEY ("prepared_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "final_settlements" ADD CONSTRAINT "final_settlements_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "final_settlements" ADD CONSTRAINT "final_settlements_paid_by_fkey" FOREIGN KEY ("paid_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE cascade;