ALTER TABLE "companies" ADD COLUMN "zakat_registration" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "zakat_registration_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "saudi_arabia_visa" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "saudi_arabia_visa_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "investment_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "investment_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "import_export_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "import_export_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "pharmaceutical_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "pharmaceutical_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "food_safety_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "food_safety_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "construction_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "construction_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "transportation_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "transportation_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "banking_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "banking_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "insurance_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "insurance_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "telecom_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "telecom_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "energy_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "energy_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "mining_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "mining_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "tourism_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "tourism_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "education_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "education_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "healthcare_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "healthcare_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "real_estate_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "real_estate_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "legal_services_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "legal_services_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "accounting_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "accounting_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "advertising_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "advertising_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "media_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "media_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "security_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "security_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "cleaning_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "cleaning_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "catering_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "catering_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "warehouse_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "warehouse_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "logistics_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "logistics_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "maintenance_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "maintenance_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "training_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "training_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "consulting_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "consulting_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "research_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "research_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "technology_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "technology_license_expiry" date;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "innovation_license" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "innovation_license_expiry" date;